# Generated by Django 4.2 on 2023-04-16 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0006_fotografia_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografia',
            new_name='Biblioteca',
        ),
    ]
