# Generated by Django 4.2 on 2023-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_rename_fotografia_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='categoria',
            field=models.CharField(choices=[('LITERATURA INFANTIL', 'Literatura Infantil'), ('LITERATURA JUVENIL', 'Literatura Juvenil'), ('FICÇÃO', 'Ficção'), ('AUTOBIOGRAFIA', 'Autobiografia')], default='', max_length=100),
        ),
    ]
