# Generated by Django 4.2 on 2023-04-16 03:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0008_biblioteca_emprestado_alter_biblioteca_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblioteca',
            new_name='Livro',
        ),
    ]
