# Generated by Django 4.2 on 2023-11-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_livro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome',
            new_name='animal',
        ),
    ]
