# Generated by Django 4.2 on 2023-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_rename_nome_livro_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='animal',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='legenda',
            new_name='nome_pop',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='descricao',
            new_name='observação',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='classe',
            field=models.CharField(choices=[('AVE', 'Ave'), ('MAMÍFERO', 'Mamífero'), ('RÉPTIL', 'Réptil'), ('ANFÍBIO', 'Anfíbio')], default='', max_length=100),
        ),
    ]
