# Generated by Django 4.2 on 2023-11-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_rename_autor_livro_especie_rename_animal_livro_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome_pop',
            new_name='nome_popular',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='emprestado',
        ),
        migrations.AddField(
            model_name='livro',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('INDETERMINADO', 'Indeterminado')], default='', max_length=100),
        ),
    ]
