# Generated by Django 4.2 on 2023-11-16 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_rename_nome_pop_livro_nome_popular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_fotografia',
            new_name='data_entrada',
        ),
        migrations.AddField(
            model_name='livro',
            name='data_saida',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='livro',
            name='motivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='origem',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
