# Generated by Django 4.2 on 2023-11-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_rename_data_fotografia_livro_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='origem',
            field=models.CharField(max_length=100),
        ),
    ]
