# Generated by Django 4.2 on 2023-11-16 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_alter_livro_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_saida',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
